/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppiic.gui;

import apppiic.network.WritableGUI;

import java.io.IOException;


/**
 *
 * @author Pedro Capelo
 */
public class Passwords extends javax.swing.JFrame {



    /**
     * Creates new form Passwords
     */
    public Passwords() {
        initComponents();
    }
 WritableGUI gui;
    int port,niveis; 
    String host,hostname;
    
    
    public Passwords(WritableGUI gui,int port, String host, String hostname,int nivel){
        initComponents();
        this.gui=gui;
        this.port=port;
        this.host=host;
        this.hostname=hostname;
        this.niveis=nivel;
        if(nivel==1){
          levelSecure.setText(Integer.toString(nivel)+" Low");
        }
        if(nivel==2){
            levelSecure.setText(Integer.toString(nivel)+" Medium");
        }
        if(nivel==3){
            levelSecure.setText(Integer.toString(nivel)+" High");
        }
       
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileImportance = new javax.swing.JLabel();
        passText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        enterButtoj = new javax.swing.JButton();
        levelSecure = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileImportance.setText("File Importance:");

        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Autentication Pass:");

        enterButtoj.setText("Enter");
        enterButtoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtojActionPerformed(evt);
            }
        });

        levelSecure.setText("LevelSecure");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterButtoj)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileImportance)
                        .addGap(27, 27, 27)
                        .addComponent(levelSecure))
                    .addComponent(jLabel1)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileImportance)
                    .addComponent(levelSecure))
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(enterButtoj)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtojActionPerformed
    
                if("password1".equals(passText.getText())&&niveis==1){
                    SaveFile savefile=new SaveFile(gui,host,port,1,"password1");
                    savefile.setVisible(true);
                    dispose();
                } 
           
                if("password2".equals(passText.getText())&&niveis==2){
                    SaveFile savefile=new SaveFile(gui,host,port,2,"password2");
                    savefile.setVisible(true);
                    dispose();
                }
          
                if("password3".equals(passText.getText())&&niveis==3){
                    SaveFile savefile=new SaveFile(gui,host,port,3,"password3");
                    savefile.setVisible(true);
                    dispose();
                } 
                else{
                    passText.setText("Wrong Password...");
                }
                
               
        
    }//GEN-LAST:event_enterButtojActionPerformed

    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passwords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passwords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passwords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passwords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passwords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FileImportance;
    private javax.swing.JButton enterButtoj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel levelSecure;
    private javax.swing.JTextField passText;
    // End of variables declaration//GEN-END:variables
}
